name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWER:${{ github.sha }} .
          docker push ghcr.io/$REPO_LOWER:${{ github.sha }}

      - name: Update CHANGELOG
        run: |
          echo "## [$(git describe --tags --always)] - $(date +%Y-%m-%d)" >> CHANGELOG.md
          git log --pretty=format:"- %s" HEAD^..HEAD >> CHANGELOG.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG"
          git push origin main

      - name: Tag Version  
        if: github.ref == 'refs/heads/main'
        run: |
          git tag -a v1.1.0 -m "Release v1.1.0"
          git push origin v1.1.0

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          github-comment: false
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .